### ISSUE TITLE
prepare, review and submit report for Milestone: "Complete system design"

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#38]
- [x] first draft is prepared
- [x] team review is done
- [x] final draft is prepared
- [x] final team review is done
- [x] report is submitted for Milestone: "Complete system design"

**Comment by kartalerkoc** [comment]
First draft has been prepared. Please review and make your **comments** so that we can prepare the final draft based on those comments. Please **do not edit** before each member completes their review on the whole draft.  You can find the first draft in following link;
https://docs.google.com/document/d/1rCJLaJucmy0ZrFPrp49E50uOBwsrFHze868ssABr2k4/edit

**Comment by yaseminalpay** [comment]
i think it'a very good work, but i have concerns if it has to be this detailed for later milestone reports.
This can be very time consuming, i think we should discuss it with Suzan.

i remember it was enough to put it with an informal format on github wiki page.
